name: Trigger Netlify Build

on:
  push:
    branches:
      - main

jobs:
  notify-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK_URL }}